#!/bin/bash
# Aᴜᴛʜᴏʀ » UᴍᴜT KᴀRᴀ
# https://t.me/umutkaratools

w='\e[1;97m'
r='\e[1;31m'
g='\e[1;32m'
y='\e[1;33m'
scriptName=`basename "$0"`

if [[ $1 == -e || $1 == --edit  ]];then
	if [[ -a $PREFIX/bin/vim ]];then
		vim $0
	fi
	exit
fi

if [[ ! -a $PREFIX/bin/curl ]];then
	printf "\n\n\n${g}
	\r\t╔═══════════════════╗
	\r\t║ ✅ ${w}CᴜʀL Kᴜʀᴜʟᴜʏᴏʀ ${g}║
	\r\t╚═══════════════════╝\n\n\n"
	pkg install curl -y
fi

if [[ ! -a $PREFIX/bin/jq ]];then
	printf "\n\n\n${g}
	\r\t╔═════════════════╗
	\r\t║ ✅ ${w}Jq Kᴜʀᴜʟᴜʏᴏʀ ${g}║
	\r\t╚═════════════════╝\n\n\n"
	pkg install jq -y
fi

function _options () {
	clear
	printf "\n${r}
	\r\t╔════════════════╗
	\r\t║ ${w}Ｏｐｔｉｏｎｓ ${r}║
	\r\t╚════════════════╝\n${y}
	\r\t╔════════════════════════════════════════════════╗
	\r\t║ 🔸 ${w}borderCreate -f false 'Example Word Output' ${y}║
	\r\t╚════════════════════════════════════════════════╝\n
	\r\t╔══════════════════════════════════════════════════════════════╗
	\r\t║ 🔸 ${w}borderCreate -f thin 'Ｅxａｍｐｌｅ Wｏｒｄ Ｏｕｔｐｕｔ' ${y}║
	\r\t╚══════════════════════════════════════════════════════════════╝\n
	\r\t╔═══════════════════════════════════════════════╗
	\r\t║ 🔸 ${w}borderCreate -f tiny 'Exᴀᴍᴘʟᴇ Wᴏʀᴅ Oᴜᴛᴘᴜᴛ' ${y}║
	\r\t╚═══════════════════════════════════════════════╝\n
	\r\t╔════════════════════════════════════════════════════╗
	\r\t║ 🔸 ${w}borderCreate -f monoSpace '𝙴x𝚊𝚖𝚙𝚕𝚎 W𝚘𝚛𝚍 𝙾𝚞𝚝𝚙𝚞𝚝' ${y}║
	\r\t╚════════════════════════════════════════════════════╝\n${g}
	\r\t╔══════════════════════════════════════════════════╗
	\r\t║  ${w}borderCreate -c --copy ${g}|${y} Sᴄʀɪᴘᴛ Cʀᴇᴀᴛᴇ Sʜᴏʀᴛᴄᴜᴛ ${g}║
	\r\t╚══════════════════════════════════════════════════╝\n\n\n"
	exit
}

if [[ $1 == -c || $1 == --copy ]];then
	
	# Sᴄʀɪᴘᴛ Cʀᴇᴀᴛᴇ Sʜᴏʀᴛᴄᴜᴛ
	if [[ ! -a $PREFIX/bin/$scriptName ]];then
		cp $0 $PREFIX/bin
		chmod 777 $PREFIX/bin/$0
		printf "${g}
		\r\t╔════════════════════════════════╗
		\r\t║ ✅ ${w}Sᴄʀɪᴘᴛ Kɪꜱᴀʏᴏʟᴜ Oʟᴜꜱᴛᴜʀᴜʟᴅᴜ ${g}║
		\r\t╚════════════════════════════════╝\n\n\n"
		exit
	else
		printf "${g}
		\r\t╔═══════════════════════════════════════╗
		\r\t║ ✅ ${w}Sᴄʀɪᴘᴛ Kɪꜱᴀʏᴏʟᴜ Zᴀᴛᴇɴ Oʟᴜꜱᴛᴜʀᴜʟᴍᴜꜱ ${g}║
		\r\t╚═══════════════════════════════════════╝\n\n\n"
		if [[ $0 != $PREFIX/bin/$scriptName ]];then
			read -e -p $'\t\e[1;97m[ \e[32mDᴇɢɪꜱᴛɪʀɪʟꜱɪɴ Mɪ? \e[33m[ʏ/N] \e[97m] \e[32m~ \e[31m»»\e[97m ' scriptChange
			printf "\n\n\n"
			if [[ $scriptChange == y || $scriptChange == Y ]];then
				rm $PREFIX/bin/$scriptName
				cp $0 $PREFIX/bin
				chmod 777 $PREFIX/bin/$0
				printf "${g}
				\r\t╔════════════════════════╗
				\r\t║ ✅ ${w}Sᴄʀɪᴘᴛ Dᴇɢɪꜱᴛɪʀɪʟᴅɪ ${g}║
				\r\t╚════════════════════════╝\n\n\n"
			fi
		fi
		exit
	fi
fi



if [[ $1 == "" || $1 != -f || $2 == "" || $3 == "" ]];then
	_options
fi

word=$(echo -e "$3")

_letters="abccdefgghiijklmnoopqrsstuuvwxyzABCCDEFGGHIIJKLMNOOPQRSSTUUVWYXZ1234567890"

letters="abcçdefgğhıijklmnoöpqrsştuüvwxyzABCÇDEFGĞHİIJKLMNOÖPQRSŞTUÜVWXYZ1234567890"

thinLetters="ａｂｃｃｄｅｆｇｇｈｉｉｊｋｌｍｎｏｏｐｑｒｓｓｔｕｕｖｗｘｙｚＡＢＣＣＤＥＦＧＧＨＩＩＪＫＬＭＮＯＯＰＱＲＳＳＴＵＵＶＷＹＸＺ１２３４５６７８９０"

# SAYI PARANTEZ KARAKTERLER

tinyLetters="ᴀʙᴄᴄᴅᴇғɢɢʜɪɪᴊᴋʟᴍɴᴏᴏᴘϙʀꜱꜱᴛᴜᴜᴠᴡxʏᴢABCCDEFGGHIIJKLMNOOPQRSSTUUVWYXZ𝟷𝟸𝟹𝟺𝟻𝟼𝟽𝟾𝟿𝟶"

monoSpaceLetters="𝚊𝚋𝚌𝚌𝚍𝚎𝚏𝚐𝚐𝚑𝚒𝚒𝚓𝚔𝚕𝚖𝚗𝚘𝚘𝚙𝚚𝚛𝚜𝚜𝚝𝚞𝚞𝚟𝚠𝚡𝚢𝚣𝙰𝙱𝙲𝙲𝙳𝙴𝙵𝙶𝙶𝙷𝙸𝙸𝙹𝙺𝙻𝙼𝙽𝙾𝙾𝙿𝚀𝚁𝚂𝚂𝚃𝚄𝚄𝚅𝚆𝚈𝚇𝚉𝟷𝟸𝟹𝟺𝟻𝟼𝟽𝟾𝟿𝟶"

Status="False"


if [[ $2 == tiny ]];then
	Status="True"
	word=$(echo -e "$word" | sed "y/$letters/$tinyLetters/")
fi

if [[ $2 == monoSpace ]];then
	Status="True"
	word=$(echo -e "$word" | sed "y/$letters/$monoSpaceLetters/")
fi

if [[ $2 == false || $2 != thin ]];then
	Status="True"
fi

wordCount=$(echo "🔸 $word " |wc -m)

if [[ $2 == thin ]];then
	Status="True"
	word=$(echo -e "$word" | sed "y/$letters/$thinLetters/")
	spaceCount=$(echo -e "$word"|sed '1s/[^ \t]//g' |wc -c)
	wordCount=$(echo -e "$word" |wc -m)
	
	let wordCount+=$wordCount

	if [[ $spaceCount -gt 1 ]];then
		let spaceCount-=3
		let wordCount-=$spaceCount
	else
		let wordCount+=2
	fi
fi

if [[ $Status == False ]];then
	_options
fi

border="═"
if [[ -a $HOME/.result ]];then
	rm $HOME/.result
fi
for count in `seq 0 $wordCount`
do
	printf "$border" >> $HOME/.result
done
border=$(cat $HOME/.result)

clear
printf "\n\n\n${y}
\r\t╔$border╗
\r\t║ 🔸 ${w}$word ${y}║
\r\t╚$border╝\n\n\n"

printf "\n\n\n${g}
\r\t╔$border╗
\r\t║ ✅ ${w}$word ${g}║
\r\t╚$border╝\n\n\n"

printf "\n\n\n${g}
\r\t╔$border╗
\r\t║ ❗ ${w}$word ${g}║
\r\t╚$border╝\n\n\n"

echo -e "\n\r\t──────────────\n"

echo '
printf "\n\n\n${y}
\r\t╔'"$border"'╗
\r\t║ 🔸 ${w}'"$word"' ${y}║
\r\t╚'"$border"'╝\n\n\n"
'
printf "\n\n"
echo '
printf "\n\n\n${g}
\r\t╔'"$border"'╗
\r\t║ ✅ ${w}'"$word"' ${g}║
\r\t╚'"$border"'╝\n\n\n"
'
printf "\n\n"
echo '
printf "\n\n\n${g}
\r\t╔'"$border"'╗
\r\t║ ❗ ${w}'"$word"' ${g}║
\r\t╚'"$border"'╝\n\n\n"
'
printf "\n"

echo -e "\n\r\t──────────────\n"
