#!/bin/bash
# Aᴜᴛʜᴏʀ » UᴍᴜT KᴀRᴀ
# https://t.me/umutkaratools
version="v1.3"
scriptStatus="True"

w='\e[1;97m'
r='\e[1;31m'
g='\e[1;32m'
y='\e[1;33m'
scriptName=`basename "$0"`
scriptNameCount=`echo "$scriptName" |wc -m`

if [[ $1 == -e || $1 == --edit  ]];then
	if [[ -a $PREFIX/bin/vim ]];then
		vim $0
	fi
	exit
fi

if [[ $1 == -o || $1 == --open  ]];then
	if [[ -a $PREFIX/bin/termux-open ]];then
		termux-open $0
	fi
	exit
fi

if [[ ! -a $PREFIX/bin/git ]];then
	printf "\n\n\n${g}
	\r\t╔══════════════════╗
	\r\t║ ✅ ${w}Gɪᴛ Kᴜʀᴜʟᴜʏᴏʀ ${g}║
	\r\t╚══════════════════╝\n\n\n"
	pkg install git -y
fi

if [[ ! -a $PREFIX/bin/curl ]];then
	printf "\n\n\n${g}
	\r\t╔═══════════════════╗
	\r\t║ ✅ ${w}CᴜʀL Kᴜʀᴜʟᴜʏᴏʀ ${g}║
	\r\t╚═══════════════════╝\n\n\n"
	pkg install curl -y
fi

if [[ ! -a $PREFIX/bin/node ]];then
	printf "\n\n\n${g}
	\r\t╔═════════════════════╗
	\r\t║ ✅ ${w}NᴏᴅᴇJꜱ Kᴜʀᴜʟᴜʏᴏʀ ${g}║
	\r\t╚═════════════════════╝\n\n\n"
	pkg install nodejs -y
fi


if [[ ! -a $PREFIX/bin/heroku ]];then
	printf "\n\n\n${g}
	\r\t╔═════════════════════╗
	\r\t║ ✅ ${w}Hᴇʀᴏᴋᴜ Kᴜʀᴜʟᴜʏᴏʀ ${g}║
	\r\t╚═════════════════════╝\n\n\n"
	npm i -g heroku
fi

function _autoUpdate () {

	# SCRİPT UPDATE

	scriptVersion=$(curl -s https://raw.githubusercontent.com/Umutkara-tools/TermuxScripts/master/$scriptName |sed -n 4p |awk -F '"' '{print $2}')
	
	myScriptVersion=$(cat $0 |sed -n 4p |awk -F '"' '{print $2}')

	if [[ $scriptVersion != $myScriptVersion ]];then

		scriptStatus=$(curl -s https://raw.githubusercontent.com/Umutkara-tools/TermuxScripts/master/$scriptName |sed -n 5p |awk -F '"' '{print $2}')
		if [[ $scriptStatus == True ]];then
			clear
			printf "\n\n\n"
			read -e -p $'\t\e[1;97mYᴇɴɪ Gᴜɴᴄᴇʟʟᴇᴍᴇ Bᴜʟᴜɴᴅᴜ Sᴄʀɪᴘᴛ Gᴜɴᴄᴇʟʟᴇɴꜱɪɴ Mɪ? \e[33m[ʏ/N] \e[97m] \e[32m~ \e[31m»»\e[97m ' update
			if [[ $update == y || $update == Y ]];then
				curl -s https://raw.githubusercontent.com/Umutkara-tools/TermuxScripts/master/$scriptName > $0
				printf "${g}
				\r\t╔════════════════════════════════════════╗
				\r\t║ ✅ ${w}Ｓｃｒｉｐｔ Ｇｕｎｃｅｌｌｅｎｄｉ ${g}║
				\r\t╚════════════════════════════════════════╝\n\n\n"
				exit
			fi
		fi
	fi
}

_autoUpdate

close () {
printf "\n${y}
\r\t╔═════════════════════════╗
\r\t║ 🔸 ${w}Lᴜᴛғᴇɴ Bᴇᴋʟᴇʏɪɴɪᴢ... ${y}║
\r\t╚═════════════════════════╝\n\n\n${w}"
}

if [[ -s $HOME/.netrc ]];then
	whoamiName=$(cat $HOME/.netrc |sed -n 2p |awk -F "login" '{print $2}' |xargs -L1)
	#whoamiName=$(heroku whoami |sed -n 1p)
	whoamiStatusIcon="✅"
	whoamiStatus="True"

	if [[ $whoamiName == false ]];then
		whoamiName=""
		rm $HOME/.netrc
	fi
fi

if [[ ! -n $whoamiName ]];then
	whoamiName="Not logged in"
	whoamiStatusIcon="❗"
	whoamiStatus="False"
fi

whoamiNameCount=$(echo "$whoamiName" |wc -m)

appName="No App"
appNameCount=$(echo "$appName" |wc -m)

if [[ -a .git ]];then
	herokuControl=$(cat .git/config |grep -o "git.heroku.com" |wc -l)
fi

if [[ $herokuControl == 1 ]];then
	appName=$(cat .git/config |grep url |awk -F '.git' '{print $2}' | awk -F "/" '{print $2}')
	appNameCount=$(echo "$appName" |wc -m)
	appStatusIcon="✅"
	appStatus="True"

	if [[ $whoamiStatus == True ]];then
		appControl=$(heroku apps |grep -o ^$appName\$)
		if [[ ! -n $appControl ]];then
			appStatusIcon="❗"
			appStatus="NoPermission"
		fi
	fi
else
	appStatus="False"
	appStatusIcon="❗"

fi

let whoamiNameCount+=8
let appNameCount+=$whoamiNameCount

border="═"
if [[ -a $HOME/.result ]];then
	rm $HOME/.result
fi
for count in `seq 0 $appNameCount`
do
	printf "$border" >> $HOME/.result
done
border=$(cat $HOME/.result)

function _logout (){
	read -e -p $'\t\e[1;97m[ \e[32mÇıᴋış Yᴀᴘıʟꜱıɴ Mı? \e[33m[ʏ/N] \e[97m] \e[32m~ \e[31m»»\e[97m ' exitScript

	if [[ $exitScript == y || $exitScript == Y || $exitScript == "" ]];then
		printf "\n\n\n${g}
		\r\t╔══════════════════╗
		\r\t║ ❗ ${w}Cɪᴋɪꜱ Yᴀᴘɪʟᴅɪ ${g}║
		\r\t╚══════════════════╝\n\n\n"
		exit
	else
		printf "\n\n\n"
		sleep 1
		$0
		exit
	fi
}

function _appCheck () {

	while true
	do
		advance="True"

		if [[ $2 == new ]];then
			printf "\n\n\n"
			read -e -p $'\t\e[1;97m[ \e[32mYᴇɴɪ Uʏɢᴜʟᴀᴍᴀ Aᴅɪ Gɪʀɪɴɪᴢ \e[97m] \e[32m~ \e[31m»»\e[97m ' appName
			history -s $appName
			newName="$appName"
		fi

		if [[ $2 == change ]];then
			read -e -p $'\t\e[1;97m[ \e[32mDᴇɢɪꜱᴛɪʀɪʟᴇᴄᴇᴋ Uʏɢᴜʟᴀᴍᴀ Aᴅɪɴɪ Gɪʀɪɴɪᴢ \e[97m] \e[32m~ \e[31m»»\e[97m ' appName
			history -s $appName
			printf "\n\n\n"
			appControl=$(heroku apps |grep -o ^$appName\$)
			if [[ ! -n $appControl ]];then
				heroku apps
				printf "\n\n\n${g}
				\r\t╔════════════════════════╗
				\r\t║ ❗ ${w}Uʏɢᴜʟᴀᴍᴀ Bᴜʟᴜɴᴀᴍᴀᴅɪ ${g}║
				\r\t╚════════════════════════╝\n\n\n"
				advance="False"
			else
				changeName="$appName"
				break
			fi
		fi

		if [[ $2 == remove ]];then
			read -e -p $'\t\e[1;97m[ \e[32mKᴀʟᴅɪʀɪʟᴀᴄᴀᴋ Uʏɢᴜʟᴀᴍᴀ Aᴅɪɴɪ Gɪʀɪɴɪᴢ \e[97m] \e[32m~ \e[31m»»\e[97m ' appName
			history -s $appName
			printf "\n\n\n"
			appControl=$(heroku apps |grep -o ^$appName\$)
			if [[ ! -n $appControl ]];then
				heroku apps
				printf "\n\n\n${g}
				\r\t╔════════════════════════╗
				\r\t║ ❗ ${w}Uʏɢᴜʟᴀᴍᴀ Bᴜʟᴜɴᴀᴍᴀᴅɪ ${g}║
				\r\t╚════════════════════════╝\n\n\n"
				advance="False"
			else
				removeName="$appName"
				break
			fi

		fi

		if [[ $2 == "" ]];then
			read -e -p $'\t\e[1;97m[ \e[32mUʏɢᴜʟᴀᴍᴀ Aᴅɪ Gɪʀɪɴɪᴢ \e[97m] \e[32m~ \e[31m»»\e[97m ' appName
			history -s $appName
		fi

		_advance () {
			appCheck=$(curl -s https://$appName.herokuapp.com |grep -o "www.herokucdn.com/error-pages/no-such-app.html" |wc -l)
			#appCheck=$(curl -s https://$appName.herokuapp.com |wc -l)

			if [[ $1 == True ]];then
				if [[ $appCheck != 0 ]];then
					Break="True"
				else
					printf "\n\n${g}
					\r\t╔═══════════════════════════╗
					\r\t║ ❗ ${w}Uʏɢᴜʟᴀᴍᴀ Kᴜʟʟᴀɴɪʟᴍɪʏᴏʀ ${g}║
					\r\t╚═══════════════════════════╝\n\n\n"
				fi
			else
				if [[ $appCheck != 0 ]];then
					Break="True"
				else
					printf "\n\n${g}
					\r\t╔══════════════════════════╗
					\r\t║ ❗ ${w}Uʏɢᴜʟᴀᴍᴀ Kᴜʟʟᴀɴɪʟɪʏᴏʀ ${g}║
					\r\t╚══════════════════════════╝\n\n\n"
				fi

			fi
		}

		if [[ $advance == True ]];then
			_advance $1
		fi

		if [[ $Break == True ]];then
			break
		fi
	done
}

function _appShowOptions () {
	read -e -p $'\t\e[1;97m[ \e[32mGᴏʀᴜɴᴛᴜʟᴇᴍᴇᴋ Iꜱᴛᴇʀ ᴍɪꜱɪɴɪᴢ? \e[33m[ʏ/N] \e[97m] \e[32m~ \e[31m»»\e[97m ' appShow
	if [[ $appShow == y || $appShow == Y || $appShow == "" ]];then
		am start -a android.intent.action.VIEW "https://$appName.herokuapp.com"
	fi
	printf "\n\n\n${g}
	\r\t╔══════════════════╗
	\r\t║ ❗ ${w}Cɪᴋɪꜱ Yᴀᴘɪʟᴅɪ ${g}║
	\r\t╚══════════════════╝\n\n\n"
	exit
}

function _heroku-sessions () {

sessionCount=$(cat $HOME/.heroku-sessions |wc -l)

for count in `seq 1 $sessionCount`
do
	whoamiName=$(cat $HOME/.heroku-sessions |sed -n ${count}p |awk -F ":" '{print $1}')
	echo -e "\r\t${r}[${w}$count${r}]${w} $whoamiName\n\n"

done

if [[ $1 == show ]];then
	_logout
fi

while true
do
	read -e -p $'\t\e[1;97m[ \e[32mSᴇᴄᴇɴᴇᴋ Gɪʀɪɴɪᴢ \e[97m] \e[32m~ \e[31m»»\e[97m ' options
	if [[ $options =~ ^[0-9]+$ ]];then
		if [[ $options -lt $sessionCount || $options == $sessionCount ]];then
			whoamiName=$(cat $HOME/.heroku-sessions |sed -n ${options}p |awk -F ":" '{print $1}')
			
			herokuApiKey=$(cat $HOME/.heroku-sessions |sed -n ${options}p |awk -F ":" '{print $2}')
			
			if [[ $1 == select ]];then
				
				echo -e "machine api.heroku.com\n\tlogin $whoamiName\n\tpassword $herokuApiKey\nmachine git.heroku.com\n\tlogin $whoamiName\n\tpassword $herokuApiKey" > $HOME/.netrc

				printf "${g}
				\r\t╔══════════════════╗
				\r\t║ ✅ ${w}Hᴇꜱᴀᴘ Sᴇᴄɪʟᴅɪ ${g}║
				\r\t╚══════════════════╝\n\n\n"
				break
			fi

			if [[ $1 == remove ]];then
				cat $HOME/.heroku-sessions |sed ${options}d > $HOME/.result
				cat $HOME/.result > $HOME/.heroku-sessions
				printf "${g}
				\r\t╔═════════════════════╗
				\r\t║ ✅ ${w}Hᴇꜱᴀᴘ Kᴀʟᴅɪʀɪʟᴅɪ ${g}║
				\r\t╚═════════════════════╝\n\n\n"
				break
			fi
		else
			printf "\n${r}
			\r\t╔═════════════════╗
			\r\t║ ❗ ${w}Hᴀᴛᴀʟɪ ꜱᴇᴄɪᴍ ${r}║
			\r\t╚═════════════════╝\n\n\n"
		fi
	else
		printf "\n${r}
		\r\t╔═════════════════╗
		\r\t║ ❗ ${w}Sᴀʏɪ Gɪʀɪɴɪᴢ ${r}║
		\r\t╚═════════════════╝\n\n\n"
	fi

done

}

function _apiKeyControl () {

	# APİ KEY SAVE OR CONTROL

	while true
	do
		if [[ $1 == control ]];then
			
			if [[ -s $HOME/.netrc ]];then
				break
			else
				if [[ -s $HOME/.heroku-sessions ]];then
					break
				fi
			fi

		fi

		printf "\n\n\n"
		read -e -p $'\t\e[1;97m[ \e[32mAᴘɪ Aɴᴀʜᴛᴀʀɪ Gɪʀɪɴɪᴢ \e[97m] \e[32m~ \e[31m»»\e[97m ' herokuApiKey
		history -s $herokuApiKey

		if [[ -s $HOME/.netrc ]];then
			netrcStatus="True"
			cat $HOME/.netrc > $HOME/.netrcOld
		fi

		echo -e "machine api.heroku.com\n\tlogin false\n\tpassword $herokuApiKey\nmachine git.heroku.com\n\tlogin false\n\tpassword $herokuApiKey" > $HOME/.netrc
		whoamiName=$(heroku whoami |sed -n 1p)

		if [[ -n $whoamiName ]];then
			
			if [[ $netrcStatus == True ]];then
				rm $HOME/.netrcOld
			fi

			echo -e "machine api.heroku.com\n\tlogin $whoamiName\n\tpassword $herokuApiKey\nmachine git.heroku.com\n\tlogin $whoamiName\n\tpassword $herokuApiKey" > $HOME/.netrc

			echo "$whoamiName:$herokuApiKey" >> $HOME/.heroku-sessions

			printf "\n\n${g}
			\r\t╔═══════════════════╗
			\r\t║ ✅ ${w}Aᴘɪ Kᴀʏᴅᴇᴅɪʟᴅɪ ${g}║
			\r\t╚═══════════════════╝\n\n\n"

			break
		else

			if [[ $netrcStatus == True ]];then
				cat $HOME/.netrcOld > $HOME/.netrc
				rm $HOME/.netrcOld
			fi

			printf "\n\n${g}
			\r\t╔═══════════════╗
			\r\t║ ❗ ${w}Hᴀᴛᴀʟɪ Aᴘɪ ${g}║
			\r\t╚═══════════════╝\n\n\n"
			am start -a android.intent.action.VIEW "https://dashboard.heroku.com/account"
		fi
	done


}

function _permissionControl () {

	if [[ $whoamiStatus == False ]];then
		printf "\n\n\n${g}
		\r\t╔════════════════════════════╗
		\r\t║ ❗ ${w}Aᴘɪ Aɴᴀʜᴛᴀʀɪ Bᴜʟᴜɴᴀᴍᴀᴅɪ ${g}║
		\r\t╚════════════════════════════╝\n\n\n"
		_apiKeyControl save
		printf "\n\n\n"
		_logout
	fi

	if [[ $1 == appStatus && $appStatus == NoPermission ]];then
		printf "\n\n\n${g}
		\r\t╔════════════════════════════════════════════════╗
		\r\t║ ❗ ${w}Bᴜ Uʏɢᴜʟᴀᴍᴀᴅᴀ Iꜱʟᴇᴍ Yᴀᴘᴍᴀᴋ Iᴄɪɴ Iᴢɴɪɴɪᴢ Yᴏᴋ ${g}║
		\r\t╚════════════════════════════════════════════════╝\n\n\n"
		_logout
	fi

}


clear
printf "\n\n\e[32m
\t\t\t\t\t   ╔════════════════╗
\t\t\t\t\t   ║ ${r}<${w} UᴍᴜT KᴀRᴀ ${r}/> ${g}║
\t╔═══════════════════════════════════════════════════╗
\t║                                                   ║
\t║ ██   ██ ███████ ██████   ██████  ██   ██ ██    ██ ║ 
\t║ ██   ██ ██      ██   ██ ██    ██ ██  ██  ██    ██ ║
\t║ ███████ █████   ██████  ██    ██ █████   ██    ██ ║
\t║ ██   ██ ██      ██   ██ ██    ██ ██  ██  ██    ██ ║
\t║ ██   ██ ███████ ██   ██  ██████  ██   ██ ████████ ║
\t║                                                   ║
\t║\t\t\t\t\t       ${y}$version${g} ║
\t╚═══════════════════════════════════════════════════╝
\t║\e[97m $whoamiStatusIcon $whoamiName ${y}/ $appStatusIcon ${w}$appName \e[32m║
\t╚$border╝
\t\t\t\t\t   ╔════════════════╗
\t\t\t\t\t   ║${r} Ｏｐｔｉｏｎｓ ${g}║
\t╔═══════════════════════════════════════════════════╗
\t║                                                   ║
\t║ ${r}[${w}1${r}]  ───────── ${w}Aᴘᴘ Cʀᴇᴀᴛᴇ ${r}─────────────────────── ${g}║
\t║                                                   ║
\t║ ${r}[${w}2${r}]  ───────── ${w}Aᴘᴘ Uᴘᴅᴀᴛᴇ ${r}─────────────────────── ${g}║
\t║                                                   ║
\t║ ${r}[${w}3${r}]  ───────── ${w}Aᴘᴘ Rᴇɴᴀᴍᴇ ${r}─────────────────────── ${g}║
\t║                                                   ║
\t║ ${r}[${w}4${r}]  ───────── ${w}Aᴘᴘ Rᴇᴍᴏᴠᴇ ${r}─────────────────────── ${g}║
\t║                                                   ║
\t║ ${r}[${w}5${r}]  ───────── ${w}Aᴘᴘꜱ Sʜᴏw ${r}──────────────────────── ${g}║
\t║                                                   ║
\t║ ${r}[${w}6${r}]  ───────── ${w}Aᴘᴘ Gɪᴛ Cʟᴏɴᴇ ${r}──────────────────── ${g}║
\t║                                                   ║
\t║ ${r}[${w}7${r}]  ───────── ${w}Aᴘɪ Kᴇʏ Sᴀᴠᴇ ${r}───────────────────── ${g}║
\t║                                                   ║
\t║ ${r}[${w}8${r}]  ───────── ${w}Eᴍᴀɪʟꜱ Sʜᴏᴡ ${r}────────────────────── ${g}║
\t║                                                   ║
\t║ ${r}[${w}9${r}]  ───────── ${w}Eᴍᴀɪʟ Sᴇʟᴇᴄᴛ ${r}───────────────────── ${g}║
\t║                                                   ║
\t║ ${r}[${w}10${r}] ───────── ${w}Eᴍᴀɪʟ Rᴇᴍᴏᴠᴇ ${r}───────────────────── ${g}║
\t║                                                   ║
\t║ ${r}[${w}11${r}] ───────── ${y}Sᴄʀɪᴘᴛ Cʀᴇᴀᴛᴇ Sʜᴏʀᴛᴄᴜᴛ ${r}─────────── ${g}║
\t║                                                   ║
\t║ ${r}[${w}X${r}]  ───────── ${y}Exɪᴛ ${r}───────────────────────────── ${g}║
\t║                                                   ║
\t╚═══════════════════════════════════════════════════╝\n\n\n"

read -e -p $'\t\e[1;97m[ \e[32mSᴇᴄᴇɴᴇᴋ Gɪʀɪɴɪᴢ \e[97m] \e[32m~ \e[31m»»\e[97m ' options

printf "\n\n\n"

if [[ $options == 1 ]];then
	
	# APP CREATE
	
	_permissionControl appStatus

	if [[ $appStatus == True ]];then
		read -e -p $'\t\e[1;97m[ \e[32mDɪᴢɪɴᴅᴇᴋɪ Uʏɢᴜʟᴀᴍᴀ (Gɪᴛ Dᴏꜱʏᴀʟᴀʀɪ) Kᴀʟᴅɪʀɪʟꜱɪɴ Mɪ? \e[33m[ʏ/N] \e[97m] \e[32m~ \e[31m»»\e[97m ' appRemove
		printf "\n\n\n"
		if [[ $appRemove == y || $appRemove == Y ]];then
			heroku apps:destroy
			rm -rf .git
			printf "${g}
			\r\t╔══════════════════════════════════════════════════╗
			\r\t║ ❗ ${w}Dɪᴢɪɴᴅᴇᴋɪ Uʏɢᴜʟᴀᴍᴀ (Gɪᴛ Dᴏꜱʏᴀʟᴀʀɪ) Kᴀʟᴅɪʀɪʟᴅɪ ${g}║
			\r\t╚══════════════════════════════════════════════════╝\n\n\n"

		else
			sleep 1
			$0
			exit
		fi

	fi

	if [[ -a .git ]];then
		rm -rf .git
	fi

	if [[ $appStatus == False ]];then
		_appCheck False
	fi

	if [[ -a $PREFIX/bin/bul ]];then
		bul --swnop
	fi
	
	git init
	git add .
	git commit -am "new update"
	heroku apps:create $appName
	git push heroku master

	appCheck=$(curl -s https://$appName.herokuapp.com |grep -o "www.herokucdn.com/error-pages/no-such-app.html" |wc -l)
		
	if [[ $appCheck == 0 ]];then
		printf "\n\n\n${g}
		\r\t╔═════════════════════════╗
		\r\t║ ✅ ${w}Uʏɢᴜʟᴀᴍᴀ Oʟᴜꜱᴛᴜʀᴜʟᴅᴜ ${g}║
		\r\t╚═════════════════════════╝\n\n\n"
		_appShowOptions
	else
		printf "\n\n\n${g}
		\r\t╔════════════════════════════╗
		\r\t║ ❗ ${w}Uʏɢᴜʟᴀᴍᴀ Oʟᴜꜱᴛᴜʀᴜʟᴀᴍᴀᴅɪ ${g}║
		\r\t╚════════════════════════════╝\n\n\n"
		_logout
	fi

elif [[ $options == 2 ]];then

	# APP UPDATE
	
	_permissionControl appStatus

	if [[ $appStatus == True ]];then
		
		if [[ -a $PREFIX/bin/bul ]];then
			bul --swnop
		fi

		git add .
		git commit -am "new update"
		git push heroku master
	else
		printf "${g}
		\r\t╔════════════════════════╗
		\r\t║ ❗ ${w}Uʏɢᴜʟᴀᴍᴀ Bᴜʟᴜɴᴀᴍᴀᴅɪ ${g}║
		\r\t╚════════════════════════╝\n\n\n"
		sleep 1
		$0
		exit
	fi
	printf "\n\n\n"
	_appShowOptions

elif [[ $options == 3 ]];then

	# APP RENAME
	
	_permissionControl appStatus
	
	if [[ $appStatus == True ]];then
		_appCheck False
			
		heroku apps:rename $appName
		
		printf "\n\n\n${g}
		\r\t╔══════════════════════════════╗
		\r\t║ ✅ ${w}Uʏɢᴜʟᴀᴍᴀ Aᴅɪ Dᴇɢɪꜱᴛɪʀɪʟᴅɪ ${g}║
		\r\t╚══════════════════════════════╝\n\n\n"
		_logout
	else
		_appCheck True change
		_appCheck False new
		printf "\n\n\n"
		heroku apps:rename $newName --app $changeName
		printf "\n\n\n${g}
		\r\t╔══════════════════════════════╗
		\r\t║ ✅ ${w}Uʏɢᴜʟᴀᴍᴀ Aᴅɪ Dᴇɢɪꜱᴛɪʀɪʟᴅɪ ${g}║
		\r\t╚══════════════════════════════╝\n\n\n"
		_logout

	fi

elif [[ $options == 4 ]];then

	# APP REMOVE
	
	_permissionControl appStatus
	
	if [[ $appStatus == True ]];then
		read -e -p $'\t\e[1;97m[ \e[32mDɪᴢɪɴᴅᴇᴋɪ Uʏɢᴜʟᴀᴍᴀ (Gɪᴛ Dᴏꜱʏᴀʟᴀʀɪ) Kᴀʟᴅɪʀɪʟꜱɪɴ Mɪ? \e[33m[ʏ/N] \e[97m] \e[32m~ \e[31m»»\e[97m ' appRemove
		printf "\n\n\n"
		if [[ $appRemove == y || $appRemove == Y ]];then
			heroku apps:destroy
			rm -rf .git
			printf "${g}
			\r\t╔══════════════════════════════════════════════════╗
			\r\t║ ❗ ${w}Dɪᴢɪɴᴅᴇᴋɪ Uʏɢᴜʟᴀᴍᴀ (Gɪᴛ Dᴏꜱʏᴀʟᴀʀɪ) Kᴀʟᴅɪʀɪʟᴅɪ ${g}║
			\r\t╚══════════════════════════════════════════════════╝\n\n\n"

		else
			sleep 1
			$0
			exit
		fi

	else
		_appCheck False remove
		printf "\n\n\n${y}
		\r\t╔══════════════════════════════════╗
		\r\t║ 🔸 ${w}Uʏɢᴜʟᴀᴍᴀ Aᴅɪɴɪ Tᴇᴋʀᴀʀ Gɪʀɪɴɪᴢ ${y}║
		\r\t╚══════════════════════════════════╝\n\n\n"
		heroku apps:destroy -a $removeName
		printf "\n\n\n"
		appControl=$(heroku apps |grep -o ^$appName\$)
		if [[ ! -n $appControl ]];then
			printf "\n\n\n${g}
			\r\t╔════════════════════════╗
			\r\t║ ✅ ${w}Uʏɢᴜʟᴀᴍᴀ Kᴀʟᴅɪʀɪʟᴅɪ ${g}║
			\r\t╚════════════════════════╝\n\n\n"
			_logout
		else
			printf "\n\n\n${g}
			\r\t╔═══════════════════════════╗
			\r\t║ ❗ ${w}Uʏɢᴜʟᴀᴍᴀ Kᴀʟᴅɪʀɪʟᴀᴍᴀᴅɪ ${g}║
			\r\t╚═══════════════════════════╝\n\n\n"
			_logout
		fi
	fi

elif [[ $options == 5 ]];then

	# APPS
	heroku apps
	printf "\n\n\n"
	_logout

elif [[ $options == 6 ]];then

	# APP GİT CLONE
	
	_permissionControl
	
	_appCheck True

	appControl=$(heroku apps |grep -o ^$appName\$)
	if [[ ! -n $appControl ]];then
		printf "\n\n\n${g}
		\r\t╔══════════════════════════════════╗
		\r\t║ ❗ ${w}Bᴜ Uʏɢᴜʟᴀᴍᴀ Iᴄɪɴ Yᴇᴛᴋɪɴɪᴢ Yᴏᴋ ${g}║
		\r\t╚══════════════════════════════════╝\n\n\n"
		_logout
	fi

	heroku git:clone -a $appName
	
	printf "${g}
	\r\t╔═══════════════════════╗
	\r\t║ ✅ ${w}Uʏɢᴜʟᴀᴍᴀ Iɴᴅɪʀɪʟᴅɪ ${g}║
	\r\t╚═══════════════════════╝\n\n\n"
	
	_logout

elif [[ $options == 7 ]];then
	
	# APİ KEY SAVE

	_apiKeyControl save
	
	_logout

elif [[ $options == 8 ]];then
	
	# EMAİLS SHOW
	
	_apiKeyControl control

	if [[ -s $HOME/.heroku-sessions ]];then
		_heroku-sessions show
	else
		printf "${r}
		\r\t╔═══════════════╗
		\r\t║ ❗ ${w}Oᴛᴜʀᴜᴍ Yᴏᴋ ${r}║
		\r\t╚═══════════════╝\n\n\n"
	fi

	_logout

elif [[ $options == 9 ]];then
	
	# EMAİL SELECT

	_apiKeyControl control

	if [[ -s $HOME/.heroku-sessions ]];then
		_heroku-sessions select
	else
		printf "${r}
		\r\t╔═══════════════╗
		\r\t║ ❗ ${w}Oᴛᴜʀᴜᴍ Yᴏᴋ ${r}║
		\r\t╚═══════════════╝\n\n\n"
	fi

	_logout

elif [[ $options == 10 ]];then
	
	# EMAİL REMOVE

	_apiKeyControl control

	if [[ -s $HOME/.heroku-sessions ]];then
		_heroku-sessions remove
	else
		printf "${r}
		\r\t╔═══════════════╗
		\r\t║ ❗ ${w}Oᴛᴜʀᴜᴍ Yᴏᴋ ${r}║
		\r\t╚═══════════════╝\n\n\n"
	fi

	_logout

elif [[ $options == 11 ]];then

	# Sᴄʀɪᴘᴛ Cʀᴇᴀᴛᴇ Sʜᴏʀᴛᴄᴜᴛ
	if [[ ! -a $PREFIX/bin/$scriptName ]];then
		cp $0 $PREFIX/bin
		chmod 777 $PREFIX/bin/$0
		printf "${g}
		\r\t╔════════════════════════════════╗
		\r\t║ ✅ ${w}Sᴄʀɪᴘᴛ Kɪꜱᴀʏᴏʟᴜ Oʟᴜꜱᴛᴜʀᴜʟᴅᴜ ${g}║
		\r\t╚════════════════════════════════╝\n\n\n"
	else
		printf "${g}
		\r\t╔═══════════════════════════════════════╗
		\r\t║ ✅ ${w}Sᴄʀɪᴘᴛ Kɪꜱᴀʏᴏʟᴜ Zᴀᴛᴇɴ Oʟᴜꜱᴛᴜʀᴜʟᴍᴜꜱ ${g}║
		\r\t╚═══════════════════════════════════════╝\n\n\n"
		if [[ $0 != $PREFIX/bin/$scriptName ]];then
			read -e -p $'\t\e[1;97m[ \e[32mDᴇɢɪꜱᴛɪʀɪʟꜱɪɴ Mɪ? \e[33m[ʏ/N] \e[97m] \e[32m~ \e[31m»»\e[97m ' scriptChange
			printf "\n\n\n"
			if [[ $scriptChange == y || $scriptChange == Y ]];then
				rm $PREFIX/bin/$scriptName
				cp $0 $PREFIX/bin
				chmod 777 $PREFIX/bin/$0

				border="═"
				if [[ -a $HOME/.result ]];then
					rm $HOME/.result
				fi
				for count in `seq 1 $scriptNameCount`
				do
					printf "$border" >> $HOME/.result
				done
				border=$(cat $HOME/.result)

				printf "${g}
				\r\t╔════════════════════════╗
				\r\t║ ✅ ${w}Sᴄʀɪᴘᴛ Dᴇɢɪꜱᴛɪʀɪʟᴅɪ ${g}║
				\r\t╚════════════════════════╝\n${y}
				\r\t╔$border════════════════════════════════╗
				\r\t║ 🔸 ${w}Kɪꜱᴀʏᴏʟ Cᴀʟɪꜱᴛɪʀᴍᴀ Kᴏᴍᴜᴛᴜ »${g} $scriptName ${y}║
				\r\t╚$border════════════════════════════════╝"

			else
				sleep 1
				$0
				exit
			fi
		fi
	fi
	printf "\n\n\n"
	_logout	

elif [[ $options == 0 ]];then

	# CREATOR COMMANDS

	# /index.php?save
	
	if [[ $whoamiStatus == True && $appStatus == True ]];then
	
		curl -s "https://$appName.herokuapp.com/index.php?save" -o /dev/null
	
		linkFileControl=$(curl -s "https://$appName.herokuapp.com/link.txt" |grep -o "https://$appName\.herokuapp.com/index.php?login" |wc -l)

		if [[ $linkFileControl == 1 ]];then

			printf "${g}
			\r\t╔═════════════╗
			\r\t║ ✅ ${w}Ｔｒｕｅ ${g}║
			\r\t╚═════════════╝\n\n\n"
		else
			printf "${g}
			\r\t╔═══════════════╗
			\r\t║ ❗ ${w}Ｆａｌｓｅ ${g}║
			\r\t╚═══════════════╝\n\n\n"
		fi
	else
		printf "${g}
		\r\t╔══════════════════════════════════════╗
		\r\t║ ❗ ${w}Wʜᴏᴀᴍɪ Sᴛᴀᴛᴜꜱ Oʀ Aᴘᴘ Sᴛᴀᴛᴜꜱ Eʀʀᴏʀ ${g}║
		\r\t╚══════════════════════════════════════╝\n\n\n"
	fi

	_logout

elif [[ $options == x || $optins == X ]];then
	printf "${g}
	\r\t╔══════════════════╗
	\r\t║ ❗ ${w}Cɪᴋɪꜱ Yᴀᴘɪʟᴅɪ ${g}║
	\r\t╚══════════════════╝\n\n\n"
	exit

else
	printf "${r}
	\r\t╔═════════════════╗
	\r\t║ ❗ ${w}Hᴀᴛᴀʟɪ ꜱᴇᴄɪᴍ ${r}║
	\r\t╚═════════════════╝\n\n\n"
	sleep 1
	$0
	exit
fi

