#!/bin/bash

# VARİABLES | START

t='✅'
f='❗'
i='🔸'
w='\e[1;97m'
r='\e[1;31m'
g='\e[1;32m'
y='\e[1;33m'
b='\e[1;34m'
c='\e[1;36m'

scriptName=$(basename $0)

# VARİABLES | END

# PACKAGE CONTROL | START

if [[ ! -a "$PATH/python" ]]; then
    echo -e "\n\n${w}python bulunamadı. ${r}[ ! ]${w}\n\nPaket kuruluyor..."
    pkg install python -y
fi

#if ! pip show qrcode > /dev/null 2>&1; then
if [[ $(find $PREFIX/lib -type f |grep "qrcode.py" |wc -l) == 0 ]]; then
    echo -e "\n\n${w}qrcode modülü bulunamadı. ${r}[ ! ]${w}\n\nModül kuruluyor..."
    pip install qrcode[pil]
fi

#if ! pip show pillow > /dev/null 2>&1; then
if [[ $(find $PREFIX/lib -type f |grep "pillow" |wc -l) == 0 ]]; then
    echo -e "\n\n${w}pillow modülü bulunamadı. ${r}[ ! ]${w}\n\nModül kuruluyor..."
    pip install pillow
fi

if [[ ! -a "$PATH/zbarimg" ]]; then
    echo -e "\n\n${w}zbarimg bulunamadı. ${r}[ ! ]${w}\n\nPaket kuruluyor..."
    pkg install zbar -y
fi

if [[ ! -a "$PATH/qr" ]]; then
    echo -e "\n\n${w}qr bulunamadı. ${r}[ ! ]${w}\n\n"
    exit
fi

# curl -s 'http://api.qrserver.com/v1/create-qr-code/?data=HelloWorld!&size=100x100'

# curl -X POST -F "file=@test.png" "https://api.qrserver.com/v1/read-qr-code/"

# PACKAGE CONTROL | END

# ARGUMENTS CONTROL & HELP MESSAGE | START 

if [[ ! -n $@ ]]; then
    clear
    echo -e "\n\n${g}
    \r\t██   ██ ███████ ██      ██████ 
    \r\t██   ██ ██      ██      ██   █  
    \r\t███████ █████   ██      ██████  
    \r\t██   ██ ██      ██      ██     
    \r\t██   ██ ███████ ███████ ██ \n\n
    \r${r} ───────────────────────────────────────────\n\n${g}
    \r${g} $scriptName ${y}( -g | --generate ) ${w}'TİTLE' 'STRİNG' \n
    \r${g} $scriptName ${y}( -s | --scan ) ${w}'FILE' \n
    \r${g} $scriptName ${y}( -f | --formule ) ${w}'MOD' 'BARCODE' \n
    "
    exit
fi

# ARGUMENTS CONTROL & HELP MESSAGE | END

#########################
# FUNCTIONS | START

printMessage () {

    # PARAMATERS : [MESSAGE] [font-family] [ red | green | yellow | noFrame ]

    if [[ ! -n $1 ]]; then
        printMessage "$f Mesaj girilmedi."
        exit
    fi
    letters="abcçdefgğhıijklmnoöpqrsştuüvwxyzABCÇDEFGĞHİIJKLMNOÖPQRSŞTUÜVWXYZ1234567890"
    tinyLetters="ᴀʙᴄᴄᴅᴇғɢɢʜɪɪᴊᴋʟᴍɴᴏᴏᴘϙʀꜱꜱᴛᴜᴜᴠᴡxʏᴢABCCDEFGGHIIJKLMNOOPQRSSTUUVWXYZ𝟷𝟸𝟹𝟺𝟻𝟼𝟽𝟾𝟿𝟶"
    thinLetters="ａｂｃｃｄｅｆｇｇｈｉｉｊｋｌｍｎｏｏｐｑｒｓｓｔｕｕｖｗｘｙｚＡＢＣＣＤＥＦＧＧＨＩＩＪＫＬＭＮＯＯＰＱＲＳＳＴＵＵＶＷＸＹＺ１２３４５６７８９０"
    monoSpaceLetters="𝚊𝚋𝚌𝚌𝚍𝚎𝚏𝚐𝚐𝚑𝚒𝚒𝚓𝚔𝚕𝚖𝚗𝚘𝚘𝚙𝚚𝚛𝚜𝚜𝚝𝚞𝚞𝚟𝚠𝚡𝚢𝚣𝙰𝙱𝙲𝙲𝙳𝙴𝙵𝙶𝙶𝙷𝙸𝙸𝙹𝙺𝙻𝙼𝙽𝙾𝙾𝙿𝚀𝚁𝚂𝚂𝚃𝚄𝚄𝚅𝚆𝚇𝚈𝚉𝟷𝟸𝟹𝟺𝟻𝟼𝟽𝟾𝟿𝟶"

    border="═"
    message="$1"

    if [[ ! -n $2 ]]; then
        message=$(echo -e "$message" |sed "y/$letters/$tinyLetters/")
    fi

    if [[ $2 == "tiny" ]]; then
        message=$(echo -e "$message" |sed "y/$letters/$tinyLetters/")
    fi

    if [[ $2 == "thin" ]]; then
        message=$(echo -e "$message" |sed "y/$letters/$thinLetters/")
    fi

    if [[ $2 == "monoSpace" ]]; then
        message=$(echo -e "$message" |sed "y/$letters/$monoSpaceLetters/")
    fi


    messageCount=$(echo -e "$message" |wc -m)
    messageLineCount=$(echo -e "$message" |wc -l)

    if [[ $message =~ ($t|$f|$i) ]];then
        ((messageCount+=1))
    fi
    
    for count in $(seq 1 $messageCount); do
        border+="═"
    done
   
    if [[ $3 == "red" ]]; then
        echo -e "\n\n${r}\r ╔$border╗\n\r ║${w} $message ${r}║\n\r ╚$border╝\n\n"
    fi
    if [[ $3 == "yellow" ]]; then
        echo -e "\n\n${y}\r ╔$border╗\n\r ║${w} $message ${y}║\n\r ╚$border╝\n\n"
    fi
    if [[ $3 == "green" || $2 == "" ]]; then
        echo -e "\n\n${g}\r ╔$border╗\n\r ║ ${w}$message ${g}║\n\r ╚$border╝\n\n"
    fi

    if [[ $3 == "noFrame" ]]; then
        echo -e "\n\n\r ${g}$message\n"
    fi
}

handleError() {
   
   # PARAMATERS : "METHOD" "VARIABLE" "MESSAGE"

   if [[ $1 == "variableCheck" ]]; then
       if [[ $2 == "" && $2 != "null" ]]; then
           printMessage "$3"
           exit
       fi
   else
       printMessage "$f Eksik Veya Hatalı Parametre Girildi. [ handleError ]"
       exit
   fi

}

# FUNCTIONS | END
#########################

if [[ $1 =~ (^-g$|^--generate$) ]];then
    handleError "variableCheck" "$2" "$f Başlık girilmedi."
    handleError "variableCheck" "$3" "$f Qr oluşturulacak metin girilmedi."

    clear
    printf "\n\n\n\n" && printMessage "\r$2" "thin" "noFrame" && qr "$3" && printf "\n\n\n\n"

    exit
fi

if [[ $1 =~ (^-s$|^--scan$) ]];then
    handleError "variableCheck" "$2" "$f Dosya girilmedi."
    if [[ ! -a $2 ]]; then
        handleError "variableCheck" "" "$f Dosya bulunamadı."
    fi

    clear
    printf "\n\n\r${g}ＱＲ ＣＯＤＥ ＯＵＴＰＵＴ\n\n${w}" && zbarimg -q "$2" |sed 's/QR-Code://g' && printf "\n\n\n\n"
    exit
fi

if [[ $1 =~ (^-f$|^--formule$) ]];then
    handleError "variableCheck" "$2" "$f Mod girilmedi."
    if [[ -n $3 ]]; then
        barcode="\"$3\""
    else
        barcode='A$1'
    fi

    clear
    printf "\n\n\n\n" && printMessage "\rFormule" "thin" "noFrame" && qr '=EĞER(A1:A750=""; "";EĞER(UZUNLUK(A1:A750)<>18; "HATALI BARKOD"; EĞERHATA(EĞER(BUL(PARÇAAL('"$barcode"'; 1; 9); A1:A750); EĞER(SATIR(A1:A750)=KAÇINCI(A1:A750; A$1:A$750; 0); EĞER(MOD(SATIR(A1:A750);'"$2"')=0;"PALET DOLDU";"✓"); "ZATEN OKUTULDU")); "FARKLI MODEL")))' && printf "\n\n\n\n"
    exit
fi
